const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const projectRoot = path.join(__dirname, '..');
const generatedHtmlPath = path.join(projectRoot, 'vocabulary-flashcards.html');
const indexHtmlPath = path.join(projectRoot, 'index.html');

test('生成页面带有禁止直接编辑的构建标记', () => {
  const html = fs.readFileSync(generatedHtmlPath, 'utf8');
  assert.match(html, /^<!doctype html>\r?\n<!-- Generated by build-vocabulary\.js\. Do not edit directly\. -->/);
});

test('GitHub Pages 入口指向生成页面并保留查询参数与哈希', () => {
  const html = fs.readFileSync(indexHtmlPath, 'utf8');
  assert.match(html, /url=\.\/vocabulary-flashcards\.html/);
  assert.match(html, /window\.location\.search \+ window\.location\.hash/);
  assert.match(html, /href="\.\/vocabulary-flashcards\.html"/);
});
