const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const projectRoot = path.join(__dirname, "..");
const generatedHtmlPath = path.join(projectRoot, "vocabulary-flashcards.html");
const webHtmlPath = path.join(projectRoot, "dist", "web", "index.html");
const offlineHtmlPath = path.join(
  projectRoot,
  "dist",
  "offline",
  "vocabulary-flashcards.html",
);
const manifestPath = path.join(projectRoot, "data", "books.manifest.json");
const sourceWordbooksPath = path.join(projectRoot, "wordbooks");
const serviceWorkerPath = path.join(
  projectRoot,
  "dist",
  "web",
  "service-worker.js",
);
const indexHtmlPath = path.join(projectRoot, "index.html");
const performanceBudgets = require("../performance-budgets.json");

test("生成页面带有禁止直接编辑的构建标记", () => {
  const html = fs.readFileSync(generatedHtmlPath, "utf8");
  assert.match(
    html,
    /^<!doctype html>\r?\n<!-- Generated by build-vocabulary\.js\. Do not edit directly\. -->/,
  );
});

test("入口按协议选择在线或离线版并保留查询参数与哈希", () => {
  const html = fs.readFileSync(indexHtmlPath, "utf8");
  assert.match(html, /url=\.\/dist\/web\/index\.html/);
  assert.match(html, /window\.location\.protocol\s*===\s*"file:"/);
  assert.match(html, /"\.\/vocabulary-flashcards\.html"/);
  assert.match(html, /window\.location\.search\s*\+\s*window\.location\.hash/);
  assert.match(html, /href="\.\/dist\/web\/index\.html"/);
  assert.match(html, /href="\.\/vocabulary-flashcards\.html"/);
  assert.match(html, /Content-Security-Policy/);
  assert.match(html, /name="referrer" content="no-referrer"/);
  const inlineScript = html.match(/<script>([\s\S]*?)<\/script>/)?.[1] || "";
  const inlineDigest = crypto
    .createHash("sha256")
    .update(inlineScript, "utf8")
    .digest("base64");
  assert.ok(html.includes(`script-src 'sha256-${inlineDigest}'`));
});

test("双构建分别生成按需在线壳与自包含离线文件", () => {
  const webHtml = fs.readFileSync(webHtmlPath, "utf8");
  const offlineHtml = fs.readFileSync(offlineHtmlPath, "utf8");
  assert.match(webHtml, /const APP_BUILD_TARGET = 'web'/);
  assert.match(webHtml, /"words":null/);
  assert.match(webHtml, /window\.location\.protocol === 'file:'/);
  assert.match(webHtml, /\.\.\/offline\/vocabulary-flashcards\.html/);
  assert.match(offlineHtml, /const APP_BUILD_TARGET = 'offline'/);
  assert.doesNotMatch(offlineHtml, /"words":null/);
});

test("词库清单保存稳定 ID、数量、Schema 与内容哈希", () => {
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  assert.equal(manifest.formatVersion, 1);
  assert.equal(manifest.books.length, 7);
  manifest.books.forEach((book) => {
    assert.match(book.id, /\.html$/);
    assert.ok(book.wordCount > 0);
    assert.match(book.contentHash, /^sha256-[a-f0-9]{64}$/);
    assert.equal(book.schemaVersion, 1);
    assert.ok(
      fs.existsSync(path.resolve(path.dirname(manifestPath), book.url)),
    );
  });
});

test("内置词书以版本化 JSON 保存且不再依赖 HTML 源文件", () => {
  const sourceFiles = fs.readdirSync(sourceWordbooksPath);
  assert.equal(
    sourceFiles.filter((fileName) => /\.html?$/i.test(fileName)).length,
    0,
  );
  const jsonFiles = sourceFiles.filter((fileName) => /\.json$/i.test(fileName));
  assert.equal(jsonFiles.length, 7);
  jsonFiles.forEach((fileName) => {
    const payload = JSON.parse(
      fs.readFileSync(path.join(sourceWordbooksPath, fileName), "utf8"),
    );
    assert.equal(payload.formatVersion, 1);
    assert.match(payload.id, /\.html$/);
    assert.ok(payload.name);
    assert.ok(Array.isArray(payload.words));
    assert.ok(payload.words.length > 0);
  });
});

test("在线构建提供版本化缓存且不强制跳过等待阶段", () => {
  const worker = fs.readFileSync(serviceWorkerPath, "utf8");
  assert.match(worker, /CACHE_NAME = 'pidanvoca-[a-f0-9]{16}'/);
  assert.match(worker, /books\.manifest\.json/);
  assert.match(worker, /clients\.claim\(\)/);
  assert.doesNotMatch(worker, /skipWaiting/);
});

test("在线与离线产物保持在已记录的体积预算内", () => {
  assert.ok(
    fs.statSync(webHtmlPath).size <= performanceBudgets.artifactBytes.webHtml,
  );
  assert.ok(
    fs.statSync(offlineHtmlPath).size <=
      performanceBudgets.artifactBytes.offlineHtml,
  );
});

function securityPolicy(html) {
  const match = html.match(
    /<meta http-equiv="Content-Security-Policy" content="([^"]+)">/,
  );
  assert.ok(match, "missing Content-Security-Policy meta tag");
  return match[1];
}

function inlineHashes(html, tagName) {
  const pattern = new RegExp(
    `<${tagName}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tagName}>`,
    "gi",
  );
  return Array.from(html.matchAll(pattern), (match) =>
    crypto.createHash("sha256").update(match[1], "utf8").digest("base64"),
  );
}

test("双产物使用哈希 CSP 限制内联脚本并禁用危险脚本属性", () => {
  [webHtmlPath, offlineHtmlPath].forEach((htmlPath) => {
    const html = fs.readFileSync(htmlPath, "utf8");
    const policy = securityPolicy(html);
    assert.match(html, /<meta name="referrer" content="no-referrer">/);
    assert.match(policy, /script-src 'self' 'sha256-/);
    assert.match(policy, /script-src-attr 'none'/);
    assert.match(policy, /worker-src 'self' blob:/);
    assert.match(policy, /object-src 'none'/);
    assert.doesNotMatch(
      policy.match(/script-src [^;]+/)?.[0] || "",
      /unsafe-inline|unsafe-eval/,
    );
    inlineHashes(html, "script").forEach((hash) => {
      assert.ok(policy.includes(`'sha256-${hash}'`));
    });
    inlineHashes(html, "style").forEach((hash) => {
      assert.ok(policy.includes(`'sha256-${hash}'`));
    });
  });
});
